- name: mysql configuration
  hosts: mysql
  become: yes
  tasks: 
  - name: install my sql server
    ansible.builtin.package:
      name: mysql-server
      state: present
  
  - name: start mysql server
    ansible.builtin.server:
      name: mysqld
      state: started
      enabled: yes